enum COLLECTIONS {
  USERS = "users",
  TASKS = "tasks",
}

enum TASK_STATUS_TYPE {
  NOT_STRTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  ARCHIVED = "ARCHIVED",
}
export { COLLECTIONS, TASK_STATUS_TYPE };
