enum COLLECTIONS {
  USERS = "users",
  TASKS = "tasks",
  PROJECTS = "projects",
}

enum TASK_STATUS_TYPE {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  WAITING = "WAITING",
  COMPLETED = "COMPLETED",
  SOMEDAY = "SOMEDAY",
  ARCHIVED = "ARCHIVED",
  DAILY_TODO = "DAILY_TODO",
}

enum PROJECT_STATUS_TYPE {
  NOT_STARTED = "NOT_STARTED",
  PLANNING = "PLANNING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  ARCHIVED = "ARCHIVED",
}

export { COLLECTIONS, TASK_STATUS_TYPE, PROJECT_STATUS_TYPE };
